# Site settings
title: Southern Ohio Trails
logo:
email: mmeyer@ovrdc.org
description: Explore Southern Ohio's Amazing Bikeways, Hiking, Bridle & and Mountain Bike Trails
about: Explore Southern Ohio's Amazing Bikeways, Hiking & Bridle Trails, and Mountain Bike Trails

baseurl: "https://ovrdc.github.io/trails-portal/" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://ovrdc.github.io/trails-portal/" #https://jekynewage.github.io" # the base hostname & protocol for your site

google_analytics: ""
addthis_id:
disqus_account:

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: flikr
    url:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
#paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
include: ["_pages"]
gems: [jekyll-paginate, jekyll-feed]

#Jekyll Collections & Defaults
collections:
  trails:
    output: true

defaults:
  - scope:
      path: ""
      type: trails
    values:
      layout: trails

#retina_magick settings:
#original images should be 1920x1280 to maintain ratios crop not current working
retinamagick:
  small:
    source: /img/homepage-images
    destination: /img/homepage-images/small
    scale: "640x427"

  medium:
    source: /img/homepage-images
    destination: /img/homepage-images/medium
    scale: "960x640"

  large:
    source: /img/homepage-images
    destination: /img/homepage-images/large
    scale: "1920x1280"

  small2:
    source: /img/trail-images
    destination: /img/trail-images/small
    scale: "640x427"

  medium2:
    source: /img/trail-images
    destination: /img/trail-images/medium
    scale: "960x640"

  large2:
    source: /img/trail-images
    destination: /img/trail-images/large
    scale: "1920x1280"

#sample images provided by pixbay
