# Site settings
host: 0.0.0.0
port: 4000
title: Southern Ohio Trails
logo:
email: mmeyer@ovrdc.org
description: Explore Southern Ohio's Amazing Bikeways, Hiking & Mountain Bike Trails
about: Explore Southern Ohio's Amazing Bikeways, Hiking, Backpacking & Mountain Bike Trails
header-img: map-header-gray.jpg
baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
#url: "http://trails.ovrdc.org" #https://jekynewage.github.io" # the base hostname & protocol for your site
url: "https://www.sohiotrails.org"
about: >-
  The Southern Ohio Trails site exists to promote Active Transportation and outdoor exploration in Southern Ohio. It is funded in part by the Ohio Department or Transportation, the Appalachian Regional Commission, the Economic Development Services Agency and OVRDC members.
  <br><br>
  The OVRDC portion of the code for this site is in the public domain and can be found on <a href="https://github.com/ovrdc/trails-portal" target="_blank">GitHub</a>.
  <br><br>
  For more information, please use the contact form on the <a href="http://www.ovrdc.org/contact" target="_blank">OVRDC website</a> and use the subject 'Trail Map', or file an issue on GitHub.

addthis_id:
# permalink: pretty
permalink:
# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: flikr
    url:

# Build settings
environment: local
markdown: kramdown
highlighter: rouge
#paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md", "Gemfile", "Gemfile.lock"]
include: ["_pages"]
#plugins: [jekyll-feed, jekyll-retinamagick]
#gems: [jekyll-paginate, jekyll-feed]
sass:
  style: compressed

#compress settings
compress_html:
  blanklines: true

#data page generation settings
page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'ovrdc_trails'
    template: 'trails'
    name: 'Name'
    dir: 'trails'

#Jekyll Collections & Defaults
collections:
  trails:
    output: true
  parks:
    output: true

defaults:
  - scope:
      path: "_trails"
      type: trails
    values:
      layout: trails
  - scope:
      path: "_parks"
      type: parks
    values:
      layout: parks
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: default
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      permalink: /blog/:year/:title/

#retina_magick settings:
#original images should be 1920x1280 to maintain ratios crop not current working
retinamagick:
  small1:
    source: /assets/img/homepage-images
    destination: /assets/img/homepage-images/small
    scale: "320x214^"
    interlace: "Plane"
    crop: "320x214-0x0"
    interlace: "Plane"
    quality: 90

  medium1:
    source: /assets/img/homepage-images
    destination: /assets/img/homepage-images/medium
    scale: "480x320^"
    crop: "480x320-0x0"
    interlace: "Plane"
    quality: 70

  large1:
    source: /assets/img/homepage-images
    destination: /assets/img/homepage-images/large
    scale: "1920x1280^"
    interlace: "Plane"
    quality: 70

  small2:
    source: /_trails/images
    destination: /trails/images/small
    scale: "320x214^"
    crop: "320x214-0x0"
    interlace: "Plane"
    quality: 90

  medium2:
    source: /_trails/images
    destination: /trails/images/medium
    scale: "640x426^"
    crop: "640x426-0x0"
    interlace: "Plane"
    quality: 70

  medium-large:
    source: /_trails/images
    destination: /trails/images/medium-large
    scale: "640x426^"
    crop: "740x495-0x0"
    interlace: "Plane"
    quality: 70

  large2:
    source: /_trails/images
    destination: /trails/images/large
    scale: "1920x1280^"
    interlace: "Plane"
    quality: 70


#sample images provided by pixbay
