# Site settings
title: Southern Ohio Trails
logo:
email: mmeyer@ovrdc.org
description: Explore Southern Ohio's Amazing Bikeways, Hiking, Bridle & and Mountain Bike Trails
about: Explore Southern Ohio's Amazing Bikeways, Hiking & Bridle Trails, and Mountain Bike Trails
header-img: map-header-gray.jpg
baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
#url: "http://trails.ovrdc.org" #https://jekynewage.github.io" # the base hostname & protocol for your site
url: "https://sohiotrails.surge.sh"
about: >-
  The Southern Ohio Trails site exists to promote Active Transportation and outdoor exploration in Southern Ohio. It is funded in part by the Ohio Department or Transportation, the Appalachian Regional Commission, the Economic Development Services Agency and OVRDC members.

  The code to this site is public domain, unless otherwise noted, and can be found on GitHub. The site is powered by Jekyll, and uses two Jekyll plugins not available in the default GitHub/Jekyll generator.

google_analytics: ""
addthis_id:
disqus_account:
permalink: pretty
# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: flikr
    url:

# Build settings
markdown: kramdown
highlighter: rouge
#paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
include: ["_pages"]
gems: [jekyll-paginate, jekyll-feed, jekyll-retinamagick]
#gems: [jekyll-paginate, jekyll-feed]
sass:
  style: compressed

#compress settings
compress_html:
  clippings: all
  comments: []
  endings: []
  ignore:
    envs: ["PRODUCTION", "local", "dev"]
  blanklines: false
  startings: [html, head, body]

#data page generation settings
page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'ovrdc_trails'
    template: 'trails'
    name: 'Name'
    dir: 'trails'


#Jekyll Collections & Defaults
collections:
  trails:
    output: true
  parks:
    output: true

defaults:
  - scope:
      path: "_trails"
      type: trails
    values:
      layout: trails
  - scope:
      path: "_parks"
      type: parks
    values:
      layout: parks
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: default

#retina_magick settings:
#original images should be 1920x1280 to maintain ratios crop not current working
retinamagick:
  small1:
    source: /assets/img/homepage-images
    destination: /assets/img/homepage-images/small
    scale: "320x214"

  medium1:
    source: /assets/img/homepage-images
    destination: /assets/img/homepage-images/medium
    scale: "480x320"
    quality: "10"

  large1:
    source: /assets/img/homepage-images
    destination: /assets/img/homepage-images/large
    scale: "1920x1280"

  small2:
    source: /_trails/images
    destination: /trails/images/small
    scale: "320x214"

  medium2:
    source: /_trails/images
    destination: /trails/images/medium
    scale: "480x320"

  large2:
    source: /_trails/images
    destination: /trails/images/large
    scale: "1920x1280"

#sample images provided by pixbay
